#!/usr/bin/env python3
"""Generate known-answer vectors for the accelerator tests.

Usage (from the repository root):
    uv run --no-project --with pycryptodome --with ecdsa \\
        eth-act-standards-tests/tools/gen_accel_vectors.py

Writes eth-act-standards-tests/accelerators/vectors/<function>.h. The headers are checked
in; this script records where every value comes from and regenerates them.

Sources:
- go-ethereum core/vm/testdata/precompiles at GETH_COMMIT, for the EVM
  precompiles. Their EVM byte encodings are converted to the C interface of
  eth-act/zkevm-standards (see include/STANDARDS_COMMIT):
    * EIP-2537 field elements drop their 16 zero padding bytes (64 -> 48).
    * EIP-196/197 points keep the EVM encoding; G2 is (x_im, x_re, y_im, y_re).
    * Boolean precompile results become the `verified` flag.
- hashlib/pycryptodome for keccak256, sha256 and ripemd160 digests.
- python-ecdsa for secp256k1 signatures, public-key recovery and checks.

Each case has one expectation:
    OK      status ZKVM_EOK and the output equals the expected bytes
    TRUE    status ZKVM_EOK and verified == true
    REJECT  status ZKVM_EFAIL, or status ZKVM_EOK and verified == false
    EFAIL   status ZKVM_EFAIL (an invalid input to a function with an output)
"""

import hashlib
import json
import urllib.request
from pathlib import Path

import ecdsa
from Crypto.Hash import RIPEMD160, keccak
from ecdsa.util import sigdecode_string, sigencode_string

GETH_COMMIT = "f5fa8e2767f171cf01e58675fd2d02d3751f5bfc"
GETH_URL = "https://raw.githubusercontent.com/ethereum/go-ethereum/{}/core/vm/testdata/precompiles/{}.json"

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "accelerators" / "vectors"
CACHE = Path.home() / ".cache" / "eth-act-standards-geth" / GETH_COMMIT

BLS_R = 0x73EDA753299D7D483339D80809A1D80553BDA402FFFE5BFEFFFFFFFF00000001


def geth(name):
    path = CACHE / f"{name}.json"
    if not path.exists():
        CACHE.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(GETH_URL.format(GETH_COMMIT, name)) as resp:
            path.write_bytes(resp.read())
    return {c["Name"]: c for c in json.loads(path.read_text())}


def unhex(s):
    return bytes.fromhex(s[2:] if s.startswith("0x") else s)


def keccak256(data):
    return keccak.new(digest_bits=256, data=data).digest()


def pattern(n, seed=0):
    return bytes((i * 131 + seed * 17 + 5) & 0xFF for i in range(n))


# --- C emission -------------------------------------------------------------


def c_array(name, data):
    body = ", ".join(f"0x{b:02x}" for b in data)
    lines = []
    for i in range(0, len(body), 96):
        lines.append("    " + body[i : i + 96].strip())
    joined = "\n".join(lines) if data else "    0"
    return f"_Alignas(8) static const uint8_t {name}[] = {{\n{joined}\n}};\n"


class Header:
    """Collects the byte arrays and case rows for one function."""

    def __init__(self, function, fields, source):
        self.function = function
        self.fields = fields  # (name, kind) with kind "bytes" (ptr + len) or "u32"/"u8"
        self.source = source
        self.arrays = []
        self.rows = []

    def case(self, label, expect, **values):
        idx = len(self.rows)
        row = [f'"{label}"', f"EXPECT_{expect}"]
        for name, kind in self.fields:
            value = values[name]
            if kind == "bytes":
                array = f"c{idx}_{name}"
                self.arrays.append(c_array(array, value))
                row += [array, str(len(value))]
            else:
                row.append(str(value))
        self.rows.append(row)

    def write(self):
        struct_fields = ["    const char *label;", "    int expect;"]
        for name, kind in self.fields:
            if kind == "bytes":
                struct_fields += [f"    const uint8_t *{name};", f"    size_t {name}_len;"]
            else:
                struct_fields.append(f"    uint32_t {name};")
        text = (
            f"/* Generated by tools/gen_accel_vectors.py; do not edit. */\n"
            f"/* {self.function}: {self.source} */\n\n"
            + "".join(self.arrays)
            + "\nstatic const struct {\n"
            + "\n".join(struct_fields)
            + "\n} cases[] = {\n"
            + "".join("    {" + ", ".join(r) + "},\n" for r in self.rows)
            + "};\n"
        )
        OUT.mkdir(parents=True, exist_ok=True)
        (OUT / f"{self.function}.h").write_text(text)


# --- EIP-2537 conversions ---------------------------------------------------


def fp48(fp64):
    assert len(fp64) == 64
    if any(fp64[:16]):
        return None  # a nonzero top byte has no 48-byte encoding
    return fp64[16:]


def fps(data):
    """Strip the padding of every 64-byte field element; None if impossible."""
    out = b""
    for i in range(0, len(data), 64):
        fp = fp48(data[i : i + 64])
        if fp is None:
            return None
        out += fp
    return out


def bls_items(data, item, scalar):
    """Convert k items of (point, [32-byte scalar]) from EIP-2537 layout."""
    size = item + (32 if scalar else 0)
    assert len(data) % size == 0
    out = b""
    for i in range(0, len(data), size):
        point = fps(data[i : i + item])
        if point is None:
            return None
        out += point + (data[i + item : i + size] if scalar else b"")
    return out


# --- generators ---------------------------------------------------------------

HASH_INPUTS = [
    ("empty", b""),
    ("abc", b"abc"),
    ("55 bytes", pattern(55)),
    ("56 bytes", pattern(56)),
    ("64 bytes", pattern(64)),
    ("135 bytes", pattern(135)),
    ("136 bytes", pattern(136)),
    ("137 bytes", pattern(137)),
    ("1000 bytes", pattern(1000, 1)),
]


def gen_hashes():
    digests = {
        "zkvm_keccak256": keccak256,
        "zkvm_sha256": lambda d: hashlib.sha256(d).digest(),
        "zkvm_ripemd160": lambda d: bytes(12) + RIPEMD160.new(d).digest(),
    }
    for function, digest in digests.items():
        h = Header(function, [("data", "bytes"), ("out", "bytes")], "reference digests of fixed inputs")
        for label, data in HASH_INPUTS:
            h.case(label, "OK", data=data, out=digest(data))
        h.write()


SECP_KEYS = [0x1, 0xC0FFEE, 0x4C0883A69102937D6231471B5DBB6204FE5129617082792AE468D01A3F362318]


def secp_sign(priv, msg):
    sk = ecdsa.SigningKey.from_secret_exponent(priv, curve=ecdsa.SECP256k1)
    digest = keccak256(msg)
    sig = sk.sign_digest_deterministic(digest, hashfunc=hashlib.sha256, sigencode=sigencode_string)
    r, s = sigdecode_string(sig, ecdsa.SECP256k1.order)
    n = ecdsa.SECP256k1.order
    if s > n // 2:
        s = n - s  # Ethereum requires low-s signatures
    pub = sk.get_verifying_key().to_string()
    return digest, r, s, pub


def recover_candidates(digest, r, s):
    sig = r.to_bytes(32, "big") + s.to_bytes(32, "big")
    return [vk.to_string() for vk in ecdsa.VerifyingKey.from_public_key_recovery_with_digest(
        sig, digest, ecdsa.SECP256k1, sigdecode=sigdecode_string, allow_truncate=False)]


def recid_for(digest, r, s, pub):
    """Recovery id: parity of R.y. python-ecdsa returns candidates in that order."""
    candidates = recover_candidates(digest, r, s)
    return candidates.index(pub)


def gen_secp256k1():
    n = ecdsa.SECP256k1.order
    rec = Header("zkvm_secp256k1_ecrecover",
                 [("msg", "bytes"), ("sig", "bytes"), ("recid", "u8"), ("out", "bytes")],
                 "python-ecdsa signatures; go-ethereum ecRecover.json cross-checked")
    ver = Header("zkvm_secp256k1_verify",
                 [("msg", "bytes"), ("sig", "bytes"), ("pubkey", "bytes")],
                 "python-ecdsa deterministic low-s signatures")
    for i, priv in enumerate(SECP_KEYS):
        digest, r, s, pub = secp_sign(priv, f"act-extra message {i}".encode())
        sig = r.to_bytes(32, "big") + s.to_bytes(32, "big")
        rec.case(f"key {i}", "OK", msg=digest, sig=sig, recid=recid_for(digest, r, s, pub), out=pub)
        ver.case(f"key {i} valid", "TRUE", msg=digest, sig=sig, pubkey=pub)
        if i == 0:
            bad_digest = bytes([digest[0] ^ 1]) + digest[1:]
            ver.case("wrong message", "REJECT", msg=bad_digest, sig=sig, pubkey=pub)
            other = secp_sign(SECP_KEYS[1], b"x")[3]
            ver.case("wrong public key", "REJECT", msg=digest, sig=sig, pubkey=other)
            ver.case("r = 0", "REJECT", msg=digest, sig=bytes(32) + sig[32:], pubkey=pub)
            ver.case("s = n", "REJECT", msg=digest, sig=sig[:32] + n.to_bytes(32, "big"), pubkey=pub)
            not_on_curve = pub[:63] + bytes([pub[63] ^ 1])
            ver.case("public key not on curve", "REJECT", msg=digest, sig=sig, pubkey=not_on_curve)
            rec.case("r = 0", "EFAIL", msg=digest, sig=bytes(32) + sig[32:], recid=0, out=bytes(64))
            rec.case("s = 0", "EFAIL", msg=digest, sig=sig[:32] + bytes(32), recid=0, out=bytes(64))
            rec.case("r = n", "EFAIL", msg=digest, sig=n.to_bytes(32, "big") + sig[32:], recid=0, out=bytes(64))

    for name, case in geth("ecRecover").items():
        data = unhex(case["Input"]).ljust(128, b"\0")
        digest, v, r, s = data[:32], int.from_bytes(data[32:64], "big"), data[64:96], data[96:128]
        if v not in (27, 28):
            continue  # the C interface takes a recovery id, not an EVM v
        expected = unhex(case["Expected"])
        if not expected:
            rec.case(f"geth {name}", "EFAIL", msg=digest, sig=r + s, recid=v - 27, out=bytes(64))
            continue
        pub = recover_candidates(digest, int.from_bytes(r, "big"), int.from_bytes(s, "big"))[v - 27]
        assert keccak256(pub)[12:] == expected[12:], name
        rec.case(f"geth {name}", "OK", msg=digest, sig=r + s, recid=v - 27, out=pub)
    rec.write()
    ver.write()


def modexp_parts(data):
    header = data[:96].ljust(96, b"\0")
    blen, elen, mlen = (int.from_bytes(header[i : i + 32], "big") for i in (0, 32, 64))
    body = data[96:].ljust(blen + elen + mlen, b"\0")
    return body[:blen], body[blen : blen + elen], body[blen + elen : blen + elen + mlen]


def gen_modexp():
    h = Header("zkvm_modexp", [("base", "bytes"), ("exp", "bytes"), ("mod", "bytes"), ("out", "bytes")],
               "go-ethereum modexp.json and modexp_eip2565.json; edge cases computed with pow()")
    cases = {**geth("modexp"), **{f"eip2565 {k}": v for k, v in geth("modexp_eip2565").items()}}
    for name in ["eip_example1", "eip_example2", "nagydani-1-square", "nagydani-1-pow0x10001",
                 "nagydani-2-qube", "eip2565 marius-1-even", "eip2565 guido-4-even",
                 "eip2565 marcin-1-exp-heavy", "eip2565 mod_vul_pawel_3_exp_8"]:
        base, exp, mod = modexp_parts(unhex(cases[name]["Input"]))
        out = unhex(cases[name]["Expected"])
        assert out == pow(int.from_bytes(base, "big"), int.from_bytes(exp, "big"),
                          int.from_bytes(mod, "big")).to_bytes(len(mod), "big"), name
        h.case(f"geth {name}", "OK", base=base, exp=exp, mod=mod, out=out)

    def own(label, base, exp, mod):
        m = int.from_bytes(mod, "big")
        value = 0 if m == 0 else pow(int.from_bytes(base, "big"), int.from_bytes(exp, "big"), m)
        h.case(label, "OK", base=base, exp=exp, mod=mod, out=value.to_bytes(len(mod), "big"))

    own("zero modulus gives zero (EVM)", pattern(32, 2), pattern(8, 3), bytes(32))
    own("empty base", b"", pattern(4, 4), pattern(32, 5))
    own("empty exponent gives 1", pattern(32, 6), b"", pattern(32, 7))
    own("modulus 1", pattern(16, 8), pattern(4, 9), b"\x01")
    own("leading zero bytes", bytes(7) + pattern(9, 10), bytes(3) + b"\x05", bytes(5) + pattern(27, 11))
    h.write()


def gen_bn254():
    add = Header("zkvm_bn254_g1_add", [("p1", "bytes"), ("p2", "bytes"), ("out", "bytes")],
                 "go-ethereum bn256Add.json (EIP-196), inputs of exactly 128 bytes")
    for name, case in geth("bn256Add").items():
        data = unhex(case["Input"])
        if len(data) == 128:
            add.case(f"geth {name}", "OK", p1=data[:64], p2=data[64:], out=unhex(case["Expected"]))
    off_curve = (1).to_bytes(32, "big") + (3).to_bytes(32, "big")
    generator = (1).to_bytes(32, "big") + (2).to_bytes(32, "big")
    add.case("point not on curve", "EFAIL", p1=off_curve, p2=generator, out=bytes(64))
    add.write()

    mul = Header("zkvm_bn254_g1_mul", [("point", "bytes"), ("scalar", "bytes"), ("out", "bytes")],
                 "go-ethereum bn256ScalarMul.json (EIP-196), inputs of exactly 96 bytes")
    for name, case in geth("bn256ScalarMul").items():
        data = unhex(case["Input"])
        if len(data) == 96:
            mul.case(f"geth {name}", "OK", point=data[:64], scalar=data[64:], out=unhex(case["Expected"]))
    mul.case("point not on curve", "EFAIL", point=off_curve, scalar=(2).to_bytes(32, "big"), out=bytes(64))
    mul.write()

    pairing = Header("zkvm_bn254_pairing", [("pairs", "bytes")],
                     "go-ethereum bn256Pairing.json (EIP-197); G2 as (x_im, x_re, y_im, y_re)")
    cases = geth("bn256Pairing")
    for name in ["jeff1", "jeff2", "jeff6", "empty_data", "one_point", "two_point_match_2",
                 "two_point_match_3", "ten_point_match_1"]:
        verdict = int.from_bytes(unhex(cases[name]["Expected"]), "big")
        pairing.case(f"geth {name}", "TRUE" if verdict == 1 else "REJECT", pairs=unhex(cases[name]["Input"]))
    jeff1 = bytearray(unhex(cases["jeff1"]["Input"]))
    jeff1[63] ^= 1
    pairing.case("G1 point not on curve", "REJECT", pairs=bytes(jeff1))
    pairing.write()


def gen_blake2f():
    h = Header("zkvm_blake2f", [("rounds", "u32"), ("h", "bytes"), ("m", "bytes"), ("t", "bytes"),
                                ("f", "u8"), ("out", "bytes")],
               "go-ethereum blake2F.json and fail-blake2f.json (EIP-152)")

    def split(data):
        return int.from_bytes(data[:4], "big"), data[4:68], data[68:196], data[196:212], data[212]

    for name, case in geth("blake2F").items():
        rounds, hh, m, t, f = split(unhex(case["Input"]))
        h.case(f"geth {name}", "OK", rounds=rounds, h=hh, m=m, t=t, f=f, out=unhex(case["Expected"]))
    for name, case in geth("fail-blake2f").items():
        data = unhex(case["Input"])
        if len(data) == 213:
            rounds, hh, m, t, f = split(data)
            h.case(f"geth {name}", "EFAIL", rounds=rounds, h=hh, m=m, t=t, f=f, out=hh)
    h.write()


def gen_kzg():
    h = Header("zkvm_kzg_point_eval", [("commitment", "bytes"), ("z", "bytes"), ("y", "bytes"), ("proof", "bytes")],
               "go-ethereum pointEvaluation.json (EIP-4844) and variants of it")
    data = unhex(geth("pointEvaluation")["pointEvaluation1"]["Input"])
    z, y, commitment, proof = data[32:64], data[64:96], data[96:144], data[144:192]
    h.case("geth pointEvaluation1", "TRUE", commitment=commitment, z=z, y=y, proof=proof)
    y_wrong = (int.from_bytes(y, "big") + 1).to_bytes(32, "big")
    h.case("wrong evaluation", "REJECT", commitment=commitment, z=z, y=y_wrong, proof=proof)
    h.case("z not a field element", "REJECT", commitment=commitment, z=BLS_R.to_bytes(32, "big"), y=y, proof=proof)
    wrong_proof = bytes([proof[0]]) + bytes([proof[1] ^ 1]) + proof[2:]
    h.case("corrupted proof", "REJECT", commitment=commitment, z=z, y=y, proof=wrong_proof)
    h.write()


def take(cases, count, predicate=lambda c: True):
    return [(n, c) for n, c in cases.items() if predicate(c)][:count]


def gen_bls():
    specs = [
        # function, geth name, point size (EIP-2537 bytes), fields, splitter
        ("zkvm_bls12_g1_add", "blsG1Add", "G1Add"),
        ("zkvm_bls12_g2_add", "blsG2Add", "G2Add"),
        ("zkvm_bls12_g1_msm", "blsG1MultiExp", "G1MSM"),
        ("zkvm_bls12_g2_msm", "blsG2MultiExp", "G2MSM"),
        ("zkvm_bls12_pairing", "blsPairing", "Pairing"),
        ("zkvm_bls12_map_fp_to_g1", "blsMapG1", "MapG1"),
        ("zkvm_bls12_map_fp2_to_g2", "blsMapG2", "MapG2"),
    ]
    for function, name, kind in specs:
        valid = geth(name)
        fail = geth("fail-" + name)
        if kind in ("G1Add", "G2Add"):
            item = 128 if kind == "G1Add" else 256
            h = Header(function, [("p1", "bytes"), ("p2", "bytes"), ("out", "bytes")],
                       f"go-ethereum {name}.json and fail-{name}.json (EIP-2537)")

            def emit(label, data, expect, out):
                p1, p2 = fps(data[:item]), fps(data[item:])
                if p1 is not None and p2 is not None:
                    h.case(label, expect, p1=p1, p2=p2, out=out)

            for n, c in take(valid, 6):
                emit(f"geth {n}", unhex(c["Input"]), "OK", fps(unhex(c["Expected"])))
            for n, c in fail.items():
                if len(unhex(c["Input"])) == 2 * item:
                    emit(f"geth {n}", unhex(c["Input"]), "EFAIL", bytes(item * 3 // 4))
        elif kind in ("G1MSM", "G2MSM"):
            item = 128 if kind == "G1MSM" else 256
            size = item + 32
            h = Header(function, [("pairs", "bytes"), ("out", "bytes")],
                       f"go-ethereum {name}.json and fail-{name}.json (EIP-2537)")
            singles = take(valid, 3, lambda c: len(unhex(c["Input"])) == size)
            multis = take(valid, 3, lambda c: len(unhex(c["Input"])) > size)
            for n, c in singles + multis:
                h.case(f"geth {n} (k={len(unhex(c['Input'])) // size})", "OK",
                       pairs=bls_items(unhex(c["Input"]), item, True), out=fps(unhex(c["Expected"])))
            for n, c in fail.items():
                data = unhex(c["Input"])
                if data and len(data) % size == 0:
                    pairs = bls_items(data, item, True)
                    if pairs is not None:
                        h.case(f"geth {n}", "EFAIL", pairs=pairs, out=bytes(item * 3 // 4))
        elif kind == "Pairing":
            h = Header(function, [("pairs", "bytes")],
                       f"go-ethereum {name}.json and fail-{name}.json (EIP-2537)")

            def convert(data):
                out = b""
                for i in range(0, len(data), 384):
                    g1, g2 = fps(data[i : i + 128]), fps(data[i + 128 : i + 384])
                    if g1 is None or g2 is None:
                        return None
                    out += g1 + g2
                return out

            ones = take(valid, 3, lambda c: unhex(c["Expected"])[-1] == 1)
            zeros = take(valid, 2, lambda c: unhex(c["Expected"])[-1] == 0)
            for n, c in ones + zeros:
                verdict = "TRUE" if unhex(c["Expected"])[-1] == 1 else "REJECT"
                h.case(f"geth {n}", verdict, pairs=convert(unhex(c["Input"])))
            for n, c in fail.items():
                data = unhex(c["Input"])
                if data and len(data) % 384 == 0:
                    pairs = convert(data)
                    if pairs is not None:
                        h.case(f"geth {n}", "REJECT", pairs=pairs)
        else:
            width = 64 if kind == "MapG1" else 128
            out_size = 96 if kind == "MapG1" else 192
            h = Header(function, [("fp", "bytes"), ("out", "bytes")],
                       f"go-ethereum {name}.json and fail-{name}.json (EIP-2537)")
            for n, c in take(valid, 5):
                h.case(f"geth {n}", "OK", fp=fps(unhex(c["Input"])), out=fps(unhex(c["Expected"])))
            for n, c in fail.items():
                data = unhex(c["Input"])
                if len(data) == width and fps(data) is not None:
                    h.case(f"geth {n}", "EFAIL", fp=fps(data), out=bytes(out_size))
        h.write()


def gen_p256():
    h = Header("zkvm_secp256r1_verify", [("msg", "bytes"), ("sig", "bytes"), ("pubkey", "bytes")],
               "go-ethereum p256Verify.json (EIP-7212, Wycheproof-derived)")
    cases = geth("p256Verify")
    valid = take(cases, 4, lambda c: unhex(c["Expected"]) != b"")
    invalid = take(cases, 4, lambda c: unhex(c["Expected"]) == b"" and len(unhex(c["Input"])) == 160)
    for n, c in valid + invalid:
        data = unhex(c["Input"])
        expect = "TRUE" if unhex(c["Expected"]) else "REJECT"
        label = n.split(": ", 1)[-1] if ": " in n else n
        h.case(f"geth {label}", expect, msg=data[:32], sig=data[32:96], pubkey=data[96:160])
    h.write()


def main():
    gen_hashes()
    gen_secp256k1()
    gen_modexp()
    gen_bn254()
    gen_blake2f()
    gen_kzg()
    gen_bls()
    gen_p256()


if __name__ == "__main__":
    main()
